[aws]
disabled=true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[character]
error_symbol = "[✖](bold red) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
