[aws]
disabled=true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[character]
error_symbol = "[✖](bold red) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1

[custom.bw]
command = "echo \"No Bitwarden session - open one with export BW_SESSION=\\`bw unlock --raw\\`\""
when = "$BW_SESSION"
